In [1]:
import numpy as np

In [ ]:
arr = np.random.randint(1,50,(5,4)) # should have been 51 instead of 50
print("arr: ",arr)

arr:  [[ 1  8 30 25]
 [40 16 13 16]
 [41 47 39 39]
 [16 10 36 18]
 [43 11 48  6]]


In [25]:
print(arr[0,-1],arr[1,-2],arr[2,-3],arr[3,-4],end="\n")

anti_diag = arr[np.arange(min(arr.shape)), arr.shape[1] - 1 - np.arange(min(arr.shape))]
print("\nAnti-diagonal elements:",anti_diag)

25 13 47 16

Anti-diagonal elements: [25 13 47 16]


In [ ]:

max = np.max(arr,axis = 1)
print("max :",max)

max : [30 40 47 36 48]


In [8]:
mean = np.mean(arr)
print("mean:",mean )

new_arr = arr[arr <=  mean]
print("new_arr :",new_arr)

mean: 25.15
new_arr : [ 1  8 25 16 13 16 16 10 18 11  6]


In [5]:
def numpy_boundary_traversal(matrix):
    # no error handeling done here
    list = []
    list.append(matrix[0,:])
    list.append(matrix[1:,-1])
    list.append(matrix[-1,-2:0:-1])
    list.append(matrix[-1:0:-1,0])
    return list 

print("traversal :",numpy_boundary_traversal(arr))

traversal : [array([ 1,  8, 30, 25], dtype=int32), array([16, 39, 18,  6], dtype=int32), array([48, 11], dtype=int32), array([43, 16, 41, 40], dtype=int32)]
